import requests
import os
import json

BASE_URL = "http://localhost:5000"

def test_health():
    try:
        resp = requests.get(f"{BASE_URL}/health")
        print(f"Health Check: {resp.status_code} - {resp.json()}")
    except Exception as e:
        print(f"Health Check Failed: {e}")

def test_verify_image(image_path, expected_status):
    if not os.path.exists(image_path):
        print(f"Skipping {image_path} (File not found)")
        return

    print(f"\nTesting Image: {image_path}")
    print(f"Expected Status: {expected_status}")

    try:
        with open(image_path, 'rb') as f:
            files = {'image': f}
            resp = requests.post(f"{BASE_URL}/verify", files=files)
            
        data = resp.json()
        print(f"Response Status: {resp.status_code}")
        print(f"AI Verdict: {data['status'].upper()}")
        
        if data['status'] == 'approved':
             print(f"Token Received: {data.get('verification_token')}")
        else:
             print(f"Rejection Reason: {data.get('reason')}")

        if data['status'] == expected_status:
            print("✅ TEST PASSED")
        else:
            print("❌ TEST FAILED")

    except Exception as e:
        print(f"Request Failed: {e}")

if __name__ == "__main__":
    print("--- Starting AI API Integration Test ---")
    test_health()
    
    # Generated by main.py
    test_images = {
        "test_images/smooth_valid.jpg": "approved", # The validator logic accepts smooth surfaces if edges are low
        "test_images/dark_valid.jpg": "approved",
        "test_images/dark_invalid.jpg": "rejected",
        "test_images/blur_invalid.jpg": "rejected",
        "test_images/screenshot_invalid.jpg": "rejected"
    }

    for img, status in test_images.items():
        test_verify_image(img, status)
